id: A19D2C122
title: A Prayer to the Vidyādhara Gurus
type: translation
pechas:
- I4CA55164
- IE6255DE6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:36.891783
  last_modified_at: 2023-01-04 11:33:36.891794
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I4CA55164/48CD: 4AA7
  IE6255DE6/D83C: 4AA7
